# Omakase Ruby styling for Rails
inherit_from: .rubocop_todo.yml
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

plugins:
  - rubocop-rails
  - rubocop-rspec

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]`

# Example override:
Layout/LineLength:
  Max: 120

# RSpec configuration - more lenient for component tests
RSpec/MultipleExpectations:
  Max: 20 

RSpec/ExampleLength:
  Max: 40

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/ContextWording:
  Enabled: false

# Metrics configuration - more lenient limits for method and class lengths
Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/RepeatedExample:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
