# Omakase Ruby styling for Rails
inherit_from: .rubocop_todo.yml
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

plugins:
  - rubocop-rails
  - rubocop-rspec

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]`

# Example override:
Layout/LineLength:
  Max: 120