# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails: rubocop.yml
  rubocop-rspec: rubocop.yml
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

require:
  - rubocop-rails
  - rubocop-rspec

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]`

# Example override:
Layout/LineLength:
  Max: 120